# This example uses the official development image for Unreal Engine 4.27, but any development image will work
FROM ghcr.io/epicgames/unreal-engine:dev-slim-5.5.4 AS builder

# Copy the source code for the project into the container
COPY --chown=ue4:ue4 . /tmp/project

# Build and package the dedicated server for the project
# (Replace "MyProject" with the name of your project)
RUN /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
	-Server -NoClient -ServerConfig=Development \
	-Project=/tmp/project/PixelCanvasExample.uproject \
	-UTF8Output -NoDebugInfo -AllMaps -NoP4 -Build -Cook -Stage -Pak -Package -Archive \
	-ArchiveDirectory=/tmp/project/Packaged \
	-Platform=Linux

# Copy the packaged files into a minimal container image
FROM gcr.io/distroless/cc-debian10:nonroot
COPY --from=builder --chown=nonroot:nonroot /tmp/project/Packaged/LinuxServer /home/nonroot/project

# Expose the port that the dedicated server listens on
EXPOSE 7777/udp

# Set the dedicated server as the container's entrypoint
# (Replace "MyProject" with the name of your project)
ENTRYPOINT ["/home/nonroot/project/PixelCanvasExample/Binaries/Linux/PixelCanvasExampleServer", "PixelCanvasExample"]